### ISSUE TITLE
Idea: Web Wormhole

### ISSUE THREAD

**Issue by thousand** [jp00p/AGIMUS#346]
Web Wormhole is a web app that can take data produced by slash commands in discord. AGIMUS can return a URL with encoded data for the user to open directly, or produce chunks of encoded data that the user copy/pastes into a buffer.

**Requirements:**
* Discord limitation of 4096 character messages in `embed` (and smaller in other places that would offer nicer UI)
* Make web client completely static/standalone for ease of hosting (potentially GHP?)
* Authenticate discord user in web client

**Work Items:**
* [ ] [MessagePack](https://msgpack.org/) data format, URL encoded
* [ ] Transaction system for multi-part payloads
  * Checksum on data completion
  * AGIMUS tracking transaction status?
* [ ] Data chunking/multi-part payloads
* [ ] LocalStorage in web app to accumulate chunks

**Comment by thousand** [comment]
Other ideas likely supported by this:
* #334 Pub Trivia
* #265 Graph trade interactions
* Admin functions for games (#215 #206)

**Comment by thousand** [comment]
WIP repo: https://github.com/thousand/agimus-wormhole
